Add `-Wno-error=array-bounds` when using GCC 14
As of today, compilation fails on Debian Trixie and Forky with
following error:

    ccache c++ -x c++    -I. -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/config -include /var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/defs.h -DLOCALEDIR="\"/build/share/locale\"" -DHAVE_CONFIG_H -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/../include/opcode -I../bfd -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/../bfd -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/../include    -I../libdecnumber -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/../libdecnumber  -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/../gnulib/import -I../gnulib/import -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/.. -I.. -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/../libbacktrace/ -I../libbacktrace/ -DTUI=1    -I/usr/include/guile/3.0  -I/usr/include/python3.13 -I/usr/include/python3.13   -I/var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/.. -pthread    -Wall -Wdeprecated-copy -Wdeprecated-copy-dtor -Wduplicated-cond -Wempty-body -Wimplicit-fallthrough=5 -Wmissing-declarations -Wno-char-subscripts -Wno-mismatched-tags -Wno-sign-compare -Wno-error=maybe-uninitialized -Wno-switch -Wno-unused -Wpointer-arith -Wredundant-move -Wshadow=local -Wstrict-null-sentinel -Wsuggest-override -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-const-variable=1 -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-value -Wunused-variable -Wvla -Wformat -Wformat-nonliteral -fsanitize=undefined -fno-sanitize-recover=undefined -Werror -O2 -g -fsanitize=address -D_GLIBCXX_DEBUG=1     -c -o symfile.o -MT symfile.o -MMD -MP -MF ./.deps/symfile.Tpo /var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/symfile.c
    In file included from /usr/include/c++/14/bits/hashtable_policy.h:36,
                     from /usr/include/c++/14/bits/hashtable.h:35,
                     from /usr/include/c++/14/bits/unordered_map.h:33,
                     from /usr/include/c++/14/unordered_map:41,
                     from /usr/include/c++/14/functional:63,
                     from /var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/../gdbsupport/ptid.h:35,
                     from /var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/../gdbsupport/common-defs.h:212,
                     from /var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/defs.h:26,
                     from <command-line>:
    In static member function 'static _Up* std::__copy_move<_IsMove, true, std::random_access_iterator_tag>::__copy_m(_Tp*, _Tp*, _Up*) [with _Tp = const add_symbol_file_command(const char*, int)::sect_opt; _Up = add_symbol_file_command(const char*, int)::sect_opt; bool _IsMove = false]',
        inlined from '_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = const add_symbol_file_command(const char*, int)::sect_opt*; _OI = add_symbol_file_command(const char*, int)::sect_opt*]' at /usr/include/c++/14/bits/stl_algobase.h:521:30,
        inlined from '_OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = false; _II = const add_symbol_file_command(const char*, int)::sect_opt*; _OI = add_symbol_file_command(const char*, int)::sect_opt*]' at /usr/include/c++/14/bits/stl_algobase.h:548:42,
        inlined from '_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = const add_symbol_file_command(const char*, int)::sect_opt*; _OI = add_symbol_file_command(const char*, int)::sect_opt*]' at /usr/include/c++/14/bits/stl_algobase.h:555:31,
        inlined from '_OI std::copy(_II, _II, _OI) [with _II = const add_symbol_file_command(const char*, int)::sect_opt*; _OI = add_symbol_file_command(const char*, int)::sect_opt*]' at /usr/include/c++/14/bits/stl_algobase.h:651:7,
        inlined from 'static _ForwardIterator std::__uninitialized_copy<true>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const add_symbol_file_command(const char*, int)::sect_opt*; _ForwardIterator = add_symbol_file_command(const char*, int)::sect_opt*]' at /usr/include/c++/14/bits/stl_uninitialized.h:147:27,
        inlined from '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const add_symbol_file_command(const char*, int)::sect_opt*; _ForwardIterator = add_symbol_file_command(const char*, int)::sect_opt*]' at /usr/include/c++/14/bits/stl_uninitialized.h:185:15,
        inlined from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, allocator<_Tp>&) [with _InputIterator = const add_symbol_file_command(const char*, int)::sect_opt*; _ForwardIterator = add_symbol_file_command(const char*, int)::sect_opt*; _Tp = add_symbol_file_command(const char*, int)::sect_opt]' at /usr/include/c++/14/bits/stl_uninitialized.h:373:37,
        inlined from 'void std::__cxx1998::vector<_Tp, _Alloc>::_M_range_initialize(_ForwardIterator, _ForwardIterator, std::forward_iterator_tag) [with _ForwardIterator = const add_symbol_file_command(const char*, int)::sect_opt*; _Tp = add_symbol_file_command(const char*, int)::sect_opt; _Alloc = std::allocator<add_symbol_file_command(const char*, int)::sect_opt>]' at /usr/include/c++/14/bits/stl_vector.h:1697:33,
        inlined from 'std::__cxx1998::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = add_symbol_file_command(const char*, int)::sect_opt; _Alloc = std::allocator<add_symbol_file_command(const char*, int)::sect_opt>]' at /usr/include/c++/14/bits/stl_vector.h:682:21,
        inlined from 'std::__debug::vector<_Tp, _Allocator>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = add_symbol_file_command(const char*, int)::sect_opt; _Allocator = std::allocator<add_symbol_file_command(const char*, int)::sect_opt>]' at /usr/include/c++/14/debug/vector:243:23,
        inlined from 'void add_symbol_file_command(const char*, int)' at /var/lib/jenkins/workspace/binutils-gdb-old/test_master/x86_64-pc-linux-gnu/src/binutils-gdb/gdb/symfile.c:2206:57:
    /usr/include/c++/14/bits/stl_algobase.h:452:30: error: 'void* __builtin_memmove(void*, const void*, long unsigned int)' forming offset 16 is out of the bounds [0, 16] [-Werror=array-bounds=]
      452 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
          |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1plus: all warnings being treated as errors

This happens with GCC 14.2 and GCC 14.3.

Until this is fixed in upstream, use `-Wno-error=array-bounds` when compiling.