Make $WORKSPACE and --prefix resolved absolute cygwin paths
...to fix builds on Windows. This is because paths like `J:\workspace\...`
become part of string via some `#define` and this causes errors like:

    ../../../bfd/plugin.c:496:30: warning: unknown escape sequence: '\w'
      496 |     = { LIBDIR "/bfd-plugins", BINDIR "/../lib/bfd-plugins" };
          |                              ^
    ../../../bfd/plugin.c:496:30: error: incomplete universal character name \u
    ../../../bfd/plugin.c:496:61: warning: unknown escape sequence: '\w'
      496 |     = { LIBDIR "/bfd-plugins", BINDIR "/../lib/bfd-plugins" };
          |                                                             ^